### PR TITLE
Bump infrastructure to v5

### PR DESCRIPTION
**Pull request by maxime-rainville**
Try bumping to infrastructure v5

Parent issue: https://github.com/silverstripeltd/product-issues/issues/694

### CODE REVIEW

**Comment by maxime-rainville** [comment]
Turns out this wasn't the problem, but hey it works.

**Comment by GuySartorelli** [comment]
If this wasn't the problem, then what does "it works" even mean? What does this change do? I don't want to merge this without knowing what it's doing.... my suspicion is actually that "infrastructure" in here does nothing (it's not documented) so we should probably just remove it instead.

**Comment by maxime-rainville** [comment]
Sorry. I should have been clearer.

It upgrades the [infrastructure from 4.5 to 5.0](https://servicedesk.silverstripe.cloud/support/solutions/articles/75000012882-infrastructure-changelog).

> ### 5.0.1 - 5 May 2023
> - Hotfix: Replace invalid SASL password for email server authentication
>
> ## 5.0.0 - 24 April 2023
> - Upgraded operating system from Ubuntu 18.04 (Bionic Beaver) and Ubuntu 22.04 (Jammy Jellyfish).
> - Base image updated to latest Ubuntu/PHP packages as of 24 April 2023. Key package versions:
>   - PHP 7.4.33, PHP 8.0.28, PHP 8.1.18, Apache 2.4.52, Nginx 1.22.1

Given that I already took the time to test it on UAT in the process of debugging the issue, it sounds reasonable to do this upgrade at the same time.

**Comment by GuySartorelli** [comment]
Does it, though? Those docs mention a checkbox in the UI. There's _no documentation what-so-ever_ about an `infrastructure` key in `.platform.yml`....

Nevertheless, I guess it's harmless. I'll merge.

**Review by GuySartorelli — APPROVED** [review]

**Comment by maxime-rainville** [comment]
When I deployed it, it clearly stated that it would upgrade us to 5.0.1

**Pull request merged**
